name: NestJS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: front-pharma

      - name: Lint code
        run: npm run lint
        working-directory: front-pharma

      - name: Run tests
        run: npm test
        working-directory: front-pharma

      - name: Build project
        run: npm run build
        working-directory: front-pharma