name: Dart CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

  install_flutter:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

  set_env_vars:
    runs-on: ubuntu-latest
    needs: install_flutter

    steps:
      - uses: actions/checkout@v4
      - name: Set up environment variables
        working-directory: mobile
        env:
          API_URL_ANDROID: ${{ secrets.API_URL_ANDROID }}
          API_URL_IOS: ${{ secrets.API_URL_IOS }}
        run: | 
          echo "API_URL_ANDROID=$API_URL_ANDROID" >> $GITHUB_ENV 
          echo "API_URL_IOS=$API_URL_IOS" >> $GITHUB_ENV

  install_dependencies:
    runs-on: ubuntu-latest
    needs: set_env_vars

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: mobile
        run: flutter pub get

  analyze:
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - uses: actions/checkout@v4
      - name: Analyze project source
        working-directory: mobile
        run: flutter analyze
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        working-directory: mobile
        run: flutter test
        continue-on-error: true