name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Set up environment variables
        working-directory: mobile
        env:
          API_URL_ANDROID: ${{ secrets.API_URL_ANDROID }}
          API_URL_IOS: ${{ secrets.API_URL_IOS }}
        run: | 
          echo "API_URL_ANDROID=$API_URL_ANDROID" >> $GITHUB_ENV 
          echo "API_URL_IOS=$API_URL_IOS" >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: mobile
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        working-directory: mobile
        run: flutter analyze

      - name: Run tests
        working-directory: mobile
        run: flutter test